# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477e7a7f48026a9135e4343e5176a7b122d91e4a31c004cf8535b8db3aff34b70ee0b03bca4cf1136136542b257397ab137fd96a0f7143f7b61798ec97a78587

test:
  secret_key_base: 89da6a1d28806b4c66fbc28c414e1ebe4b17b2139bfedbafa944e05123817e4225b76b9fb319f065a43234f274a1b956d9963a9b25587a73eebaf61188e20dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
